name: FOSSA

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  merge_group:
    types: [checks_requested]

jobs:
  fossa:
    runs-on: ubuntu-latest

    if: github.actor != 'dependabot[bot]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install FOSSA CLI
        run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash

      - name: Set FOSSA API Key
        run: echo "FOSSA_API_KEY=${{ secrets.FOSSA_PUB_API_KEY }}" >> $GITHUB_ENV

      - name: Install only production dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run FOSSA Analysis
        run: |
          fossa analyze --exclude "tests/**" --exclude "**/pylint*" --exclude "**/flake8*" --exclude "**/certbot*" --exclude "docs/**"

      - name: Run FOSSA Test
        run: fossa test

      - name: Run FOSSA Test
        run: fossa test
